TOP=../..

include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_SITE
include $(PYDEVSUP)/configure/CONFIG_PY

PY += ems.py
PY += init.py

include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
